### ISSUE TITLE
Error in the console or crash when Quaver gets moved to a voice or stage channel with insufficient text channel permissions

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#127]
**Describe the bug**
Quaver throws an error in the console when Quaver gets moved to a stage channel with insufficient permissions for accessing text channel.

Has a potential to crash with unhandledRejection here's why

It tried to send the locale string `MUSIC_FORCED_STAGE` to a text channel.
as a result from the try catch. 

But that is just one scenario of try catch that caught the error, there are many more that haven't been handled that causes unhandledRejection.

**Affected versions**
What versions of Quaver are affected by this bug? (e.g. all versions before 3.0.1, 2.5.1 to 2.6.3, all versions from 1.2.0)
All versions after 2.8.0

**To reproduce**
Make a text channel that makes everyone not able to send text messages.
1. Remove Administrator Permission
2. Play any track on a voice channel with Quaver.
3. Move Quaver to a Stage channel.
4. Quaver shall automatically disconnect but
5. See error
> console
```js
DiscordAPIError: Missing Permissions
    at RequestHandler.execute (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async TextChannel.send (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\structures\interfaces\TextBasedChannel.js:175:1
5)
    at async Client.<anonymous> (C:\Users\Ava\Documents\GitHub\Quaver\main.js:543:6) {
  method: 'post',
  path: '/channels/920107978760261663/messages',
  code: 50013,
  httpStatus: 403,
  requestData: {
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: [Array],
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    },
    files: []
  }
}
```

**Expected behavior**
Quaver should disconnect, if it doesn't have permission to send a message, it shoud `return;`.

**Comment by Xayanide** [comment]
May have been fixed by
https://github.com/ZapSquared/Quaver/commit/029b18cfd281233f7f36cda6cceead355742ac8e and https://github.com/ZapSquared/Quaver/commit/e15ab0048a0c6fe3c1a85124f02b0112557f0ac2
