### ISSUE TITLE
Quaver crashes when it reconnects to a manually ended stage channel.

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#134]
**Describe the bug**
More info: Quaver do not crash when it is moved to an already started stage channel.

Quaver doesn't work properly when it reconnects to a manually ended stage channel. It thinks that the stage channel is still open, according to the error.log it spat out.

**Affected versions**
What versions of Quaver are affected by this bug? (e.g. all versions before 3.0.1, 2.5.1 to 2.6.3, all versions from 1.2.0)
^3.3.0

**To reproduce**
1. Join any stage channel, play any track with Quaver
2. Disconnect Quaver 
3. Right click the stage channel, click on "End Stage", confirm it.
4. Play any track with Quaver again
5. Quaver shall crash
6. See error
> Console log after the reproduction steps
```js
$ node main.js
[Quaver] Connected to Discord! Logged in as ThatKid#6969.
[Quaver] Running version 3.3.0. For help, see https://github.com/ZapSquared/Quaver/issues.     
[Quaver] Connected to Lavalink!
[G 906471497231630336 | U 250934589621665793] Processing command play
[G 906471497231630336 | U 250934589621665793] Executing command play
[Quaver] Shutting down...
[Quaver] Disconnecting from all guilds...
[G 291429415488061451] Disconnecting (restarting)
[G 906471497231630336] Starting track
[G 906471497231630336] Disconnecting (restarting)
[Quaver] Logging additional output to error.log
```

> error.log
```js
unhandledRejection
The Stage is already open
DiscordAPIError: The Stage is already open
    at RequestHandler.execute (/home/runner/thatkid6969/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/runner/thatkid6969/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async StageInstanceManager.create (/home/runner/thatkid6969/node_modules/discord.js/src/managers/StageInstanceManager.js:65:18)
    at async Client.<anonymous> (/home/runner/aei/main.js:573:5)
```
> Seems like it is trying to start an already started stage channel. Tracing the stack on my instance
```js
			await newState.setSuppressed(false);
			if (!newState.channel.stageInstance) {
				await newState.channel.createStageInstance({ topic: getLocale(guildData.get(`${player.guildId}.locale`) ?? defaultLocale, 'MUSIC_STAGE_TOPIC'), privacyLevel: 'GUILD_ONLY' });
			}
		}
```

**Expected behavior**
Quaver shouldn't crash from joining a manually ended stage channel. Also stage channels that were ended from inactivity (just in case).

**Comment by Xayanide** [comment]
Seems like the issue was only reproducible on my end, probably going to reopen this if it is reproducible to the original.
