### ISSUE TITLE
Quaver crashes with DiscordAPIError: Missing Access (is back at it again)

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#156]
**Describe the bug**
Continuation for #68 
There are lot of ways to reproduce this since the beginning, it might be missing permissions for every `channel.send`, who knows.

**Affected versions**
What versions of Quaver are affected by this bug? (e.g. all versions before 3.0.1, 2.5.1 to 2.6.3, all versions from 1.2.0)
Highly likely it affects all versions.

**To reproduce**
1. Disable `Administrator` permissions
2. Play a 30 second track on voice or stage
3. Disable `VIEW_CHANNEL` or `SEND_MESSAGES` permission on the current active text channel Quaver is in.
4. Wait for the track to end
5. See error
> I added something to the shutting down function for it to log the error because Quaver currently gets stuck there waiting for something. Anyway not going into detail since this isn't for this issue, #152 for #128 should fix that.
> console
```
$ node main.js
[Quaver] Connected to Discord! Logged in as ThatKid#6969.
[Quaver] Running version 3.3.1-next.2. For help, see https://github.com/ZapSquar
ed/Quaver/issues.
[Quaver] Connected to Lavalink!
[G 906471497231630336 | U 250934589621665793] Processing command play
[G 906471497231630336 | U 250934589621665793] Executing command play
[G 906471497231630336] Starting track
[Quaver] Shutting down...
[Quaver] Disconnecting from all guilds...
[G 906471497231630336] Disconnecting (restarting)
[Quaver] Logging additional output to error.log.
```
> error.log
```
unhandledRejection
Missing Access
DiscordAPIError: Missing Access
    at RequestHandler.execute (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async TextChannel.send (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\structures\interfaces\TextBasedChannel.js:175:15)
```
another chance you will meet this again, as well
```
unhandledRejection
Missing Permissions
DiscordAPIError: Missing Permissions
    at RequestHandler.execute (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async TextChannel.send (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\structures\interfaces\TextBasedChannel.js:175:15)
```

These error stacks barely helps me either.

**Expected behavior**
Quaver should have a check before the incident happens or catch the error somehow.

Maybe `async` and `await` on every `send({`? lol

**Comment by Xayanide** [comment]
May have been fixed by
Superseded by 
https://github.com/ZapSquared/Quaver/commit/029b18cfd281233f7f36cda6cceead355742ac8e and https://github.com/ZapSquared/Quaver/commit/e15ab0048a0c6fe3c1a85124f02b0112557f0ac2
