### ISSUE TITLE
Everytime Quaver disconnects, the next voiceStateUpdate event crashes Quaver

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#173]
**Describe the bug**
What isn't working as intended, and what does it affect?
voiceStateUpdate after disconnection

Affects functionality.

**Affected versions**
What versions are affected by this bug? (e.g. >=3.0.1, 2.5.1-2.6.3, >=1.2.0)
3.4.0-next.39

**Steps to reproduce**
Steps to reproduce the behavior. (e.g. click on a button, enter a value, etc. and see error)
1. Join either voice or stage channel.
2. Play any track.
3. Disconnect Quaver in any way possible: disconnect manually, `/disconnect`, shuttingDown or pause timed out.
4. User makes a voiceStateUpdate event, either moving, disconnecting or joining a voice or stage channel.

**Expected behavior**
What is expected to happen?
Not to crash and remain if a user voiceStateUpdates after Quaver disconnects.
> Clean up unnecessarily. It should only clean up if it gets manually disconnected.

**Actual behavior**
What actually happens? Attach or add errors or screenshots here as well.
Whenever Quaver disconnects in any way possible and a human or user voiceStateUpdates crashes it, here is the console log of the entire reproduction process.
Ignore the `stage already open`, that is not the scope of this issue.
**Do note that Quaver usually does `not` do `cleaning up` when a user uses `/disconnect` on it.
> additionally, it cleans up when Quaver uses the shuttingDown function when a track is playing.

```js
> 2022-04-04T17:03:47.284Z [Discord] INFO: Connected. Logged in as ThatKid#6969.
2022-04-04T17:03:47.289Z [Quaver] INFO: Running version 3.4.0-next.39. For help, see https://github.com/ZapSquared/Quaver/issues.
2022-04-04T17:03:47.289Z [Quaver] WARN: You are running an unstable version of Quaver. Please report bugs using the link above, and note that f
eatures may change or be removed entirely prior to release.
2022-04-04T17:03:48.520Z [Lavalink] INFO: Connected.
2022-04-04T17:04:03.446Z [Quaver] INFO: [G 906471497231630336 | U 250934589621665793] Processing command play
2022-04-04T17:04:03.447Z [Quaver] INFO: [G 906471497231630336 | U 250934589621665793] Executing command play
2022-04-04T17:04:10.620Z [Quaver] ERROR: The Stage is already open
DiscordAPIError: The Stage is already open
    at RequestHandler.execute (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async StageInstanceManager.create (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\managers\StageInstanceManager.js:65:
18)
    at async Object.execute (C:\Users\Ava\Documents\GitHub\Quaver\events\voiceStateUpdate.js:44:7)
2022-04-04T17:04:11.787Z [Quaver] INFO: [G 906471497231630336] Starting track
2022-04-04T17:04:57.106Z [Quaver] INFO: [G 906471497231630336 | U 250934589621665793] Processing command disconnect
2022-04-04T17:04:57.107Z [Quaver] INFO: [G 906471497231630336 | U 250934589621665793] Executing command disconnect
2022-04-04T17:04:57.381Z [Quaver] INFO: [G 906471497231630336] Cleaning up
2022-04-04T17:05:48.421Z [Quaver] INFO: Shutting down...
2022-04-04T17:05:48.422Z [Quaver] INFO: Disconnecting from all guilds...
2022-04-04T17:05:48.423Z [Quaver] INFO: [G 906471497231630336] Disconnecting (restarting)
2022-04-04T17:05:48.832Z [Quaver] ERROR: Cannot read properties of null (reading 'members')
TypeError: Cannot read properties of null (reading 'members')
    at Object.execute (C:\Users\Ava\Documents\GitHub\Quaver\events\voiceStateUpdate.js:104:24)
    at Client.<anonymous> (C:\Users\Ava\Documents\GitHub\Quaver\main.js:161:41)
    at Client.emit (node:events:526:28)
    at VoiceStateUpdate.handle (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\client\actions\VoiceStateUpdate.js:38:14)
    at Object.module.exports [as VOICE_STATE_UPDATE] (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\client\websocket\handler
s\VOICE_STATE_UPDATE.js:4:35)
    at WebSocketManager.handlePacket (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\client\websocket\WebSocketManager.js:351
:31)
    at WebSocketShard.onPacket (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\ws\lib\event-target.js:199:18)
    at WebSocket.emit (node:events:526:28)
2022-04-04T17:05:48.833Z [Quaver] INFO: Logging additional output to error.log.
```

**Comment by zapteryx** [comment]
theoretically fixed in ad6962aa47183cd1772d10092e787fbb6f995d92
