### ISSUE TITLE
There's still a possibility for Circular dependency warnings to appear.

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#201]
**Describe the bug**
What isn't working as intended, and what does it affect?
Functionality.

**This is not really a bug for Quaver as of now, but there's still a possibility for the warnings to appear.**
Fix every possible way for this warning to show up, so we will never have to tackle with it again.

**Affected versions**
What versions are affected by this bug? (e.g. >=3.0.1, 2.5.1-2.6.3, >=1.2.0)
3.4.0-next.x

**Steps to reproduce**
Steps to reproduce the behavior. (e.g. click on a button, enter a value, etc. and see error)
1. Move some imports or statements around, e.g `main.js`

**Expected behavior**
What is expected to happen?
Warning should cease to exist completely just like before event files were implemented. 

**Actual behavior**
What actually happens? Attach or add errors or screenshots here as well.
There's still a possibility for warnings to appear.

For instance, these warnings:

This showed up after moving some imports or stuff around in my instance.
```
(node:4400) Warning: Accessing non-existent property 'bot' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object.<anonymous> (C:\Users\Ava\Documents\GitHub\Quaver\classes\MusicHandler.js:4:9)  
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Ava\Documents\GitHub\Quaver\commands\play.js:8:22)        
(node:4400) Warning: Accessing non-existent property 'shuttingDown' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object.<anonymous> (C:\Users\Ava\Documents\GitHub\Quaver\events\music\error.js:2:9)    
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Ava\Documents\GitHub\Quaver\main.js:102:16)
    ```

**Comment by Xayanide** [comment]
Issue is unrelated to Quaver's code structure.
