### ISSUE TITLE
Quaver crashes when it gets a Kick or a Ban while playing a track.

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#223]
**Describe the bug**
What isn't working as intended, and what does it affect?
Functionality
Must be fixed immediately, this is priority `-1`

**Affected versions**
What versions are affected by this bug? (e.g. >=3.0.1, 2.5.1-2.6.3, >=1.2.0)
3.4.0

**Steps to reproduce**
Steps to reproduce the behavior. (e.g. click on a button, enter a value, etc. and see error)
1. Play any track with Quaver on a voice or stage channel.
2. Give Quaver a kick or a ban.

**Expected behavior**
What is expected to happen?
Leave the server and clean up.

**Actual behavior**
What actually happens? Attach or add errors or screenshots here as well.
Crashes due to an undefined channels, an optional chaining operator might be missing somewhere.
```js
PS C:\Users\Ava\Documents\GitHub\Quaver> node .
2022-04-18T13:12:13.559Z [Discord] INFO: Connected. Logged in as Aia#3990.
2022-04-18T13:12:13.563Z [Quaver] INFO: Running version 3.4.0. For help, see https://github.com/ZapSquared/Quaver/issues.
2022-04-18T13:12:14.388Z [Lavalink] INFO: Connected.
2022-04-18T13:12:26.395Z [Quaver] INFO: [G 906471497231630336 | U 250934589621665793] Processing command play
2022-04-18T13:12:26.400Z [Quaver] INFO: [G 906471497231630336 | U 250934589621665793] Executing command play
2022-04-18T13:12:29.508Z [Quaver] INFO: [G 906471497231630336] Starting track
2022-04-18T13:12:36.259Z [Quaver] INFO: [G 906471497231630336] Cleaning up
2022-04-18T13:12:36.275Z [Discord] INFO: [G 906471497231630336] Left guild An-Environment
2022-04-18T13:12:36.281Z [Quaver] INFO: Shutting down...
2022-04-18T13:12:36.283Z [Quaver] INFO: Disconnecting from all guilds...
2022-04-18T13:12:36.285Z [Quaver] ERROR: Cannot read properties of undefined (reading 'channels')
TypeError: Cannot read properties of undefined (reading 'channels')
    at MusicHandler.disconnect (C:\Users\Ava\Documents\GitHub\Quaver\classes\MusicHandler.js:20:65)
    at Object.execute (C:\Users\Ava\Documents\GitHub\Quaver\events\guildDelete.js:10:35)
    at Client.<anonymous> (C:\Users\Ava\Documents\GitHub\Quaver\main.js:161:41)     
    at Client.emit (node:events:527:28)
    at GuildDeleteAction.handle (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\client\actions\GuildDelete.js:49:14)
    at Object.module.exports [as GUILD_DELETE] (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\client\websocket\handlers\GUILD_DELETE.js:4:30)        
    at WebSocketManager.handlePacket (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\client\websocket\WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\ws\lib\event-target.js:199:18)
2022-04-18T13:12:36.290Z [Quaver] INFO: Logging additional output to error.log.
```

**Comment by Xayanide** [comment]
Must be fixed immediately.
