### ISSUE TITLE
"TypeError: channel.send is not a function" when Quaver tries to send a message in a voice channel's text channel

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#258]
**Describe the bug**
What isn't working as intended, and what does it affect?
User experience

**Affected versions**
What versions are affected by this bug? (e.g. >=3.0.1, 2.5.1-2.6.3, >=1.2.0)
3.4.2-next.4

**Steps to reproduce**
Steps to reproduce the behavior. (e.g. click on a button, enter a value, etc. and see error)
1. Join any voice channel
2. Play any track with Quaver in the voice channel's text channel.

**Expected behavior**
What is expected to happen?
Show the "now playing" message or any messages that it was supposed to send after the interaction.

**Actual behavior**
What actually happens? Attach or add errors or screenshots here as well.
Quaver continues its functionality, while an error was thrown in the console:
```js
$ node .
2022-06-05T10:07:53.408Z [Discord] INFO: Connected. Logged in as Aia#3990.      
2022-06-05T10:07:53.411Z [Quaver] INFO: Running version 3.4.2-next.4. For help, 
see https://github.com/ZapSquared/Quaver/issues.
2022-06-05T10:07:53.412Z [Quaver] WARN: You are running an unstable version of Quaver. Please report bugs using the link above, and note that features may change or be removed entirely prior to release.
2022-06-05T10:07:58.178Z [Lavalink] INFO: Connected.
2022-06-05T10:08:09.740Z [Quaver] INFO: [G 906471497231630336 | U 250934589621665793] Processing command play
2022-06-05T10:08:09.744Z [Quaver] INFO: [G 906471497231630336 | U 250934589621665793] Executing command play
2022-06-05T10:08:17.961Z [Quaver] INFO: [G 906471497231630336] Starting track   
2022-06-05T10:08:17.967Z [Quaver] ERROR: channel.send is not a function
TypeError: channel.send is not a function
    at MusicHandler.send (C:\Users\Ava\Documents\GitHub\Quaver\classes\MusicHandler.js:72:25)
    at Object.execute (C:\Users\Ava\Documents\GitHub\Quaver\events\music\trackStart.js:17:35)
    at Node.<anonymous> (C:\Users\Ava\Documents\GitHub\Quaver\main.js:172:47)   
    at Node.emit (node:events:527:28)
    at Queue.emit (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\@lavaclient\queue\dist\Queue.js:91:26)
    at Player.<anonymous> (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\@lavaclient\queue\dist\Queue.js:32:18)
    at Player.emit (node:events:527:28)
    at Player.handleEvent (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\lavaclient\dist\lib\Player.js:198:14)
    at Connection._onmessage (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\lavaclient\dist\lib\node\Connection.js:177:15)
    at WebSocket.onMessage (C:\Users\Ava\Documents\GitHub\Quaver\node_modules\ws\lib\event-target.js:199:18)
```

**Comment by Xayanide** [comment]
To add, Quaver will not be able to shutdown properly as well.
