### ISSUE TITLE
Quaver crashes when play is being used while it is left playing on the other server.

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#56]
**Describe the bug**
Quaver crashes when play is being used while it is left playing on the other server.

**To Reproduce**
user1 is from server1
user2 is from server2

1. user1 plays Quaver on any channels and then leaves.
2. In server1, Quaver is now paused
3. user2 joins any channel
4. user2 uses play
5. Quaver's play command did not execute in server2
6. Quaver shows that it crashed in server1
```
unhandledRejection
Unknown interaction
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (C:\Users\Ava\Desktop\Quaver-3.0.0-next.2\node_modules\discord.js\src\rest\RequestHandler.js:349:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Ava\Desktop\Quaver-3.0.0-next.2\node_modules\discord.js\src\rest\RequestHandler.js:50:14)
    at async CommandInteraction.reply (C:\Users\Ava\Desktop\Quaver-3.0.0-next.2\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:98:5)
    at async Client.<anonymous> (C:\Users\Ava\Desktop\Quaver-3.0.0-next.2\main.js:250:4)
```

**Expected behavior**
Quaver shouldn't crash on this kind of situations. Quaver should be and continue operating as normal.

**Comment by Xayanide** [comment]
I will put this issue on hold as I think it was only reproduciable on my end.
